language: node_js
services:
  docker
  mongodb
  redis-server
node_js:
- '12'
branches:
  only:
  - master
install:
- npm install -g mocha
- npm install
# 启动docker
- docker build -t registry.cn-hangzhou.aliyuncs.com/movie-node/node-server:latest .
script:
- npm run test
addons:
  ssh_known_hosts: $ip
after_success:
- echo 'I successfully done'
- npm i -g pm2 && pm2 deploy ecosystem.config.js prod update
- docker login --username=伙食榜 -p=$aliyun_pwd registry.cn-hangzhou.aliyuncs.com
- docker push registry.cn-hangzhou.aliyuncs.com/movie-node/node-server:latest
before_install:
- openssl aes-256-cbc -K $encrypted_cee67c79dec3_key -iv $encrypted_cee67c79dec3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- sudo redis-server --port 6379
- sudo mongod
- ssh -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa root@$ip "cd /home/node-server;docker-compose -f docker-compose.yml pull;docker-compose -f docker-compose.yml up -d;exit"