version: '2'
networks:
  nginx_bridge:
    driver: bridge
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    # command: --config /etc/mongo/mongod.conf
    # environment:
      # - MONGO_DATA_DIR=/usr/local/mongodb/database
      # - MONGO_LOG_DIR=/usr/local/mongodb/log
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=123.com
    ports:
      - 27017:27017
    volumes:
      - /usr/local/mongodb/database:/data/db
      - /usr/local/mongodb/log:/var/log/mongodb
  redis:
    image: redis
    container_name: redis
    volumes:
      # - /usr/local/redis/dump.rdb:/usr/local/redis/dump.rdb
      - /usr/local/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # - /usr/local/redis/logs:/usr/local/redis/logs
    # command:
    # # 两个写入操作 只是为了解决启动后警告 可以去掉
    #   /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
    #   && echo never > /sys/kernel/mm/transparent_hugepage/enabled
    #   && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.19
    container_name: nginx
    restart: always
    privileged: true
    # environment:
      # - TZ=Asia/Shanghai 
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /usr/local/etc/nginx:/etc/nginx/nginx.d:ro
      - ./bin/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./bin/nginx/logs.log:/etc/nginx/logs/log.log
      - ./public:/movie/server/public:ro
      - /Users/mac/Developments/node-server/static:/movie/server/static:ro
    networks:
      - nginx_bridge
  web:
    container_name: node-server
    image: registry.cn-hangzhou.aliyuncs.com/movie-node/node-server:latest
    # image: test-web-image
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - mongo
      - redis
      # - nginx
    volumes:
      - /home/server/source:/movie_server/app
      - /home/server/source/static:/movie_server/app/static
      # - /Users/mac/Developments/node-server:/movie_server/app
      # - /Users/mac/Developments/node-server/static:/movie_server/app/static
    # command: 
    #   # - echo 'I run the docker web image'
    #   # - bash -c "npm run prod:docker"