name: Deploy server to aliyun 
on: 
  push:
    branches:
      - master 
jobs:
  deploy-and-start:
    runs-on: ubuntu-latest # 运行环境
    steps:
      # 下载代码
      - name: Checkout  
        uses: actions/checkout@master

      # 设置node 
      - name: setup node 
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - run: |
          npm install yarn pm2 -g
      # - run: |
      #     pm2 deploy pm2.config.js production update

      # # 文件上传
      # - name: deploy
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SSH_KEY }}
      #     REMOTE_HOST: ${{ secrets.SSH_IP }}
      #     REMOTE_USER: ${{ secrets.SSH_USERNAME }}
      #     ARGS: "-avz --delete"
      #     TARGET: ${{ secrets.REMOTE_PATH }}

      # 登录服务器并启动docker服务   
      - name: start the remote server 
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_IP }}
          script: |
            ls 
            cd ${{ secrets.REMOTE_PATH }}
            git pull origin master
            npm install pm2 yarn -g 
            yarn 
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
            pm2 startOrRestart pm2.config.js