name: Deploy server to aliyun 
on: 
  push:
    branches:
      - master 
jobs:
  deploy-and-start:
    runs-on: ubuntu-latest # 运行环境
    steps:
      # 下载代码
      - name: Checkout  
        uses: actions/checkout@master

      # 设置ssh文件
      - name: Setup ssh
        env:
          LOCAL_SSH_PRIVATE_KEY: ${{ secrets.LOCAL_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$LOCAL_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa

      # 设置node 
      - name: setup node 
        uses: actions/setup-node@v1
      - run: |
          npm install yarn pm2 -g
      - run: |
          pm2 deploy pm2.config.js production update

      # # 文件上传
      # - name: deploy
      #   uses: easingthemes/ssh-deploy@v2.1.1
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.LOCAL_SSH_PRIVATE_KEY }}
      #     REMOTE_HOST: ${{ secrets.SSH_IP }}
      #     REMOTE_USER: ${{ secrets.SSH_USERNAME }}
      #     ARGS: "-avz --delete"
      #     TARGET: ${{ secrets.REMOTE_PATH }}
      #     SOURCE: "./"

      # 登录服务器并启动docker服务   
      - name: start the remote server 
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_IP }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            npm install pm2 yarn -g 
            yarn 
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
            pm2 startOrRestart pm2.config.js